#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/spaceperc
#     Description: Script for piping the free space status into dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

FREE=`df /data -h | awk 'END{gsub(/%/,""); print $5}'`

ICON="diskette.xbm"
if [[ $FREE -gt 90 ]]; then
    PERCBAR=`echo -e "$FREE"\
        | gdbar -bg "#393939" -fg red -h 3 -w 50`
    ICON='^fg(red)^i(/home/arietux/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
else
    PERCBAR=`echo -e "$FREE"\
        | gdbar -bg "#393939" -fg "#A6A6A6" -h 3 -w 50`
    ICON='^i(/home/arietux/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
fi

echo "$ICON $PERCBAR"
