#!/bin/bash
# ------------------------------------------------------------------
#
#  Scripts/updcount
#  Description: Script for checking the number of updates available
#  Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

NUMBER=`pacman -Qu | wc -l`
echo "$NUMBER"
